<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  22870 => 'TOGOCEL',
  22879 => 'Moov',
  22890 => 'TOGOCEL',
  22891 => 'TOGOCEL',
  22892 => 'TOGOCEL',
  22893 => 'TOGOCEL',
  22896 => 'Moov',
  22897 => 'TOGOCEL',
  22898 => 'Moov',
  22899 => 'Moov',
);
