<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  6777 => 'Solomon Telekom',
  6778 => 'BMobile',
  6779 => 'Smile',
  67791 => 'Satsol',
  67792 => 'Satsol',
  67793 => 'Satsol',
);
