<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  99361 => 'TM-Cell',
  99362 => 'TM-Cell',
  99363 => 'TM-Cell',
  99364 => 'TM-Cell',
  99365 => 'TM-Cell',
  99366 => 'MTS (BARASH Communication)',
  99367 => 'MTS (BARASH Communication)',
  99368 => 'MTS (BARASH Communication)',
  99369 => 'MTS (BARASH Communication)',
);
