OC.L10N.register(
    "provisioning_api",
    {
    "Provisioning API" : "API hornitzen",
    "This application enables a set of APIs that external systems can use to manage users, groups and apps." : "Aplikazio honek gaitzen du kanpoko sistemek erabiltzaileak, taldeak eta aplikazioak kudeatzeko erabil ditzaketen API multzo bat.",
    "This application enables a set of APIs that external systems can use to create, edit, delete and query user\n\t\tattributes, query, set and remove groups, set quota and query total storage used in Nextcloud. Group admin users\n\t\tcan also query Nextcloud and perform the same functions as an admin for groups they manage. The API also enables\n\t\tan admin to query for active Nextcloud applications, application info, and to enable or disable an app remotely.\n\t\tOnce the app is enabled, HTTP requests can be used via a Basic Auth header to perform any of the functions\n\t\tlisted above. More information is available in the Provisioning API documentation, including example calls\n\t\tand server responses." : "Aplikazio honek gaitzen du kanpoko sistemek erabiltzailea sortu, editatu, ezabatu eta kontsultatzeko erabili ditzaketen API multzo bat\n\t\tatributuak, kontsultak, taldeak ezarri eta kendu, kuota ezarri eta Nextcloud-en erabilitako biltegiratze osoa kontsultatu. Taldeko administratzaileek\n\t\tNextcloud ere kontsulta dezakete eta administratzaile baten funtzio berdinak bete kudeatzen dituzten taldeentzako. APIak ere gaitzen du\n\t\tadministratzaile bat Nextcloud kontsultatzeko aplikazio aktiboak, aplikazioen informazioa eta aplikazio bat urrunetik gaitzeko edo desgaitzeko.\n\t\tAplikazioa gaituta dagoenean, HTTP eskaerak oinarrizko autentifikazio goiburu baten bidez erabili daitezke betetzeko\n\t\tgoian zerrendatuko edozein funtzio. Informazio gehiago eskuragarri dago API hornitze- dokumentazioan, adibide-deiak\n\t\teta zerbitzariaren erantzunak barne.",
    "This application enables a set of APIs that external systems can use to create, edit, delete and query user\n\t\tattributes, query, set and remove groups, set quota and query total storage used in Nextcloud. Group admin users\n\t\tcan also query Nextcloud and perform the same functions as an admin for groups they manage. The API also enables\n\t\tan admin to query for active Nextcloud applications, application info, and to enable or disable an app remotely.\n\t\tOnce the app is enabled, http requests can be used via a Basic Auth header to perform any of the functions\n\t\tlisted above. More information is available in the Provisioning API documentation, including example calls\n\t\tand server responses." : "Aplikazio honek gaitzen du kanpoko sistemek erabiltzailea sortu, editatu, ezabatu eta kontsultatzeko erabili ditzaketen API multzo bat\n\t\tatributuak, kontsultak, taldeak ezarri eta kendu, kuota ezarri eta Nextcloud-en erabilitako biltegiratze osoa kontsultatu. Taldeko administratzaileek\n\t\tNextcloud ere kontsulta dezakete eta administratzaile baten funtzio berdinak bete kudeatzen dituzten taldeentzako. APIak ere gaitzen du\n\t\tadministratzaile bat Nextcloud kontsultatzeko aplikazio aktiboak, aplikazioen informazioa eta aplikazio bat urrunetik gaitzeko edo desgaitzeko.\n\t\tAplikazioa gaituta dagoenean, http eskaerak oinarrizko autentifikazio goiburu baten bidez erabili daitezke betetzeko\n\t\tgoian zerrendatuko edozein funtzio. Informazio gehiago eskuragarri dago API hornitze-dokumentazioan, adibide-deiak\n\t\teta zerbitzariaren erantzunak barne."
},
"nplurals=2; plural=(n != 1);");
