OC.L10N.register(
    "provisioning_api",
    {
    "Provisioning API" : "Provisioning API",
    "This application enables a set of APIs that external systems can use to manage users, groups and apps." : "此應用程序啟用了一組 API ，外部系統可以使用這些 API 來管理用戶、組和應用程序。",
    "This application enables a set of APIs that external systems can use to create, edit, delete and query user\n\t\tattributes, query, set and remove groups, set quota and query total storage used in Nextcloud. Group admin users\n\t\tcan also query Nextcloud and perform the same functions as an admin for groups they manage. The API also enables\n\t\tan admin to query for active Nextcloud applications, application info, and to enable or disable an app remotely.\n\t\tOnce the app is enabled, HTTP requests can be used via a Basic Auth header to perform any of the functions\n\t\tlisted above. More information is available in the Provisioning API documentation, including example calls\n\t\tand server responses." : "此應用程序啟用了一組 API，外部系統可以使用它們來創建、編輯、刪除和查詢用戶\n\t\t屬性、查詢、設置和刪除組，設置配額以及查詢 Nextcloud 中使用的總存儲量。組管理員用戶\n\t\t還可以查詢 Nextcloud，並為其管理的組執行與管理員相同的功能。該 API 還支持\n\t\t管理員查詢活動的 Nextcloud 應用程序、應用程序信息，以及遠程啟用或禁用應用程序。\n\t\t啟用該應用後，可以通過基本身份驗證標頭使用 HTTP 請求執行\n以上所列任何功能。 Provisioning API 文檔中提供了更多信息，包括示例調用\n\t\t和伺服器響應。",
    "This application enables a set of APIs that external systems can use to create, edit, delete and query user\n\t\tattributes, query, set and remove groups, set quota and query total storage used in Nextcloud. Group admin users\n\t\tcan also query Nextcloud and perform the same functions as an admin for groups they manage. The API also enables\n\t\tan admin to query for active Nextcloud applications, application info, and to enable or disable an app remotely.\n\t\tOnce the app is enabled, http requests can be used via a Basic Auth header to perform any of the functions\n\t\tlisted above. More information is available in the Provisioning API documentation, including example calls\n\t\tand server responses." : "此應用程序啟用了一組 API，外部系統可以使用它們來創建、編輯、刪除和查詢用戶\n\t\t屬性、查詢、設置和刪除組，設置配額以及查詢 Nextcloud 中使用的總存儲量。組管理員用戶\n\t\t還可以查詢 Nextcloud，並為其管理的組執行與管理員相同的功能。該 API 還支持\n\t\t管理員查詢活動的 Nextcloud 應用程序、應用程序信息，以及遠程啟用或禁用應用程序。\n\t\t啟用該應用後，可以通過基本身份驗證標頭使用 HTTP 請求執行\n以上所列任何功能。 Provisioning API 文檔中提供了更多信息，包括示例調用\n\t\t和伺服器響應。"
},
"nplurals=1; plural=0;");
