<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  35813 => 'Norra Karelen',
  35814 => 'Mellersta Finland',
  35815 => 'St Michel',
  35816 => 'Lappland',
  35817 => 'Kuopio',
  35819 => 'Nyland',
  35821 => 'Åbo/Björneborg',
  35822 => 'Åbo/Björneborg',
  35823 => 'Åbo/Björneborg',
  35824 => 'Åbo/Björneborg',
  35825 => 'Åbo/Björneborg',
  35826 => 'Åbo/Björneborg',
  35827 => 'Åbo/Björneborg',
  35828 => 'Åbo/Björneborg',
  35831 => 'Tavastland',
  35832 => 'Tavastland',
  35833 => 'Tavastland',
  35834 => 'Tavastland',
  35835 => 'Tavastland',
  35836 => 'Tavastland',
  35837 => 'Tavastland',
  35838 => 'Tavastland',
  35851 => 'Kymmene',
  35852 => 'Kymmene',
  35853 => 'Kymmene',
  35854 => 'Kymmene',
  35855 => 'Kymmene',
  35856 => 'Kymmene',
  35857 => 'Kymmene',
  35858 => 'Kymmene',
  35861 => 'Vasa',
  35862 => 'Vasa',
  35863 => 'Vasa',
  35864 => 'Vasa',
  35865 => 'Vasa',
  35866 => 'Vasa',
  35867 => 'Vasa',
  35868 => 'Vasa',
  35881 => 'Uleåborg',
  35882 => 'Uleåborg',
  35883 => 'Uleåborg',
  35884 => 'Uleåborg',
  35885 => 'Uleåborg',
  35886 => 'Uleåborg',
  35887 => 'Uleåborg',
  35888 => 'Uleåborg',
  3589 => 'Helsingfors',
);
