#!/usr/bin/env php
<?php
/**
 * SPDX-FileCopyrightText: 2014 ownCloud, Inc.
 * SPDX-FileCopyrightText: 2014 Olivier Paroz
 * SPDX-FileCopyrightText: 2013 Thomas Müller <thomas.mueller@tmit.eu>
 * SPDX-License-Identifier: AGPL-3.0-only
 */

//$argv = $_SERVER['argv'];
require_once __DIR__ . '/console.php';
