#!/usr/bin/env php
<?php
/**
 * Copyright (c) 2013 Thomas Müller <thomas.mueller@tmit.eu>
 * This file is licensed under the Affero General Public License version 3 or
 * later.
 * See the COPYING-README file.
 */

// make it possible to run as root
if (posix_getuid() == 0){
	$command = implode (' ', $argv);
	echo(shell_exec('sudo -u www-data '.$command));
	exit;
}

require_once __DIR__ . '/console.php';
