# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "Nextcloud server Cypress tests"
SPDX-PackageSupplier = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/server"

[[annotations]]
path = ["fixtures/viewer/image.gif", "fixtures/viewer/image.ico", "fixtures/viewer/image.svg", "fixtures/viewer/image-small.png", "fixtures/viewer/image-apng.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"

[[annotations]]
path = ["snapshots/base/e2e/visual-regression.cy.ts/image.png", "snapshots/base/e2e/visual-regression.cy.ts/image2.png", "snapshots/base/e2e/visual-regression.cy.ts/non-dav.png", "snapshots/base/e2e/visual-regression.cy.ts/video.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["fixtures/viewer/image1.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Stephen Leonardi <https://unsplash.com/@leo_visions_> <https://unsplash.com/photos/rock-formation-with-lava-during-daytime-eSNjFDbw_i4>"
SPDX-License-Identifier = "LicenseRef-Unsplash"

[[annotations]]
path = ["fixtures/viewer/image2.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Tom Gainor <https://unsplash.com/@its_tgain> <https://unsplash.com/photos/mountain-cliff-under-starry-night-KidY3t8O4PE>"
SPDX-License-Identifier = "LicenseRef-Unsplash"

[[annotations]]
path = ["fixtures/viewer/image4.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Vincent Riszdorfer <https://unsplash.com/@theguywithacamera> <https://unsplash.com/photos/person-about-to-claim-mountain-Q6X1ifPIfjs>"
SPDX-License-Identifier = "LicenseRef-Unsplash"

[[annotations]]
path = ["fixtures/viewer/video.mkv", "fixtures/viewer/video.ogv", "fixtures/viewer/video.webm", "fixtures/viewer/video1.mp4", "fixtures/viewer/video2.mp4"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012 AnRo0002 <https://commons.wikimedia.org/wiki/User:AnRo0002>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["fixtures/viewer/test-card.mp4", "fixtures/viewer/test-card.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Bulgarian National Television <https://commons.wikimedia.org/wiki/File:Bulgarian_colour_testcard.png>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["fixtures/viewer/audio.mp3", "fixtures/viewer/audio.ogg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 AC Krah <https://commons.wikimedia.org/wiki/User:AC_Krah>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["fixtures/viewer/image3.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 Wilfredor <https://commons.wikimedia.org/wiki/User:Wilfredor>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["fixtures/viewer/image.bmp", "fixtures/viewer/image.png", "fixtures/viewer/image.webp"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Master Unknown <https://unsplash.com/@exp00>"
SPDX-License-Identifier = "LicenseRef-Unsplash"

[[annotations]]
path = ["fixtures/viewer/image.heic"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 HEIC Digital <https://heic.digital/download-sample/soundboard.heic>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["tsconfig.json", "fixtures/appstore/apps.json", "dist/*.css"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "fixtures/image.jpg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Tom Gainor <https://unsplash.com/@its_tgain> <https://unsplash.com/photos/mountain-cliff-under-starry-night-KidY3t8O4PE>"
SPDX-License-Identifier = "LicenseRef-Unsplash"