<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'OCA\\Sharing\\AppInfo\\Application' => $baseDir . '/../lib/AppInfo/Application.php',
    'OCA\\Sharing\\Capabilities' => $baseDir . '/../lib/Capabilities.php',
    'OCA\\Sharing\\Command\\AddShareRecipient' => $baseDir . '/../lib/Command/AddShareRecipient.php',
    'OCA\\Sharing\\Command\\AddShareSource' => $baseDir . '/../lib/Command/AddShareSource.php',
    'OCA\\Sharing\\Command\\CreateShare' => $baseDir . '/../lib/Command/CreateShare.php',
    'OCA\\Sharing\\Command\\DeleteShare' => $baseDir . '/../lib/Command/DeleteShare.php',
    'OCA\\Sharing\\Command\\GetShare' => $baseDir . '/../lib/Command/GetShare.php',
    'OCA\\Sharing\\Command\\ListShares' => $baseDir . '/../lib/Command/ListShares.php',
    'OCA\\Sharing\\Command\\RemoveShareRecipient' => $baseDir . '/../lib/Command/RemoveShareRecipient.php',
    'OCA\\Sharing\\Command\\RemoveShareSource' => $baseDir . '/../lib/Command/RemoveShareSource.php',
    'OCA\\Sharing\\Command\\SharingBase' => $baseDir . '/../lib/Command/SharingBase.php',
    'OCA\\Sharing\\Command\\UpdateSharePermission' => $baseDir . '/../lib/Command/UpdateSharePermission.php',
    'OCA\\Sharing\\Command\\UpdateShareProperty' => $baseDir . '/../lib/Command/UpdateShareProperty.php',
    'OCA\\Sharing\\Command\\UpdateShareState' => $baseDir . '/../lib/Command/UpdateShareState.php',
    'OCA\\Sharing\\Controller\\ApiV1Controller' => $baseDir . '/../lib/Controller/ApiV1Controller.php',
    'OCA\\Sharing\\Migration\\Version1000Date20250929161325' => $baseDir . '/../lib/Migration/Version1000Date20250929161325.php',
    'OCA\\Sharing\\ResponseDefinitions' => $baseDir . '/../lib/ResponseDefinitions.php',
);
