<?php /**
 * Copyright (c) 2011, Robin Appelman <icewind1991@gmail.com>
 * This file is licensed under the Affero General Public License version 3 or later.
 * See the COPYING-README file.
 */
 
return array(
'bg_BG'=>'български език',
'ca'=>'Català',
'cs_CZ'=>'Čeština',
'da'=>'Dansk',
'de'=>'Deutsch',
'el'=>'Ελληνικά',
'en'=>'English',
'es'=>'Español',
'et_EE'=>'Eesti',
'fr'=>'Français',
'id'=>'Bahasa Indonesia',
'it'=>'Italiano',
'lb'=>'Lëtzebuergesch',
'ms_MY'=>'Bahasa Melayu',
'nb_NO'=>'Norwegian Bokmål',
'nl'=>'Nederlands',
'pl'=>'Polski',
'pt_BR'=>'Português brasileiro',
'pt_PT'=>'Português',
'ro'=>'română',
'ru'=>'Русский язык',
'sr'=>'Српски',
'sr@latin'=>'Srpski',
'sv'=>'Svenska',
'zh_CN'=>'中文',
'sk_SK'=>'Slovenčina',
'hu_HU'=>'Magyar',
'eu'=>'Euskara',
'lt_LT'=>'Lietuvių',
'eo'=>'Esperanto',
'tr'=>'Türkçe',
'hr'=>'Hrvatski',
'ar'=>'العربية',
'he'=>'עִבְרִית,',
'ia'=>'Interlingua',
'sl'=>'Slovenski',
'nn_NO'=>'Nynorsk',
);
