# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: "ðŸ› Bug report: Nextcloud Server"
description: "Submit a report and help us improve Nextcloud Server"
title: "[Bug]: "
labels: ["bug", "0. Needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### ðŸ‘ Thank you for contributing to our project!
        Please note this is a **free and open-source** project. Most people take on their own time to help you, so please, be patient.
        You can obtain [Enterprise support](https://nextcloud.com/support/) if you run Nextcloud Server in a mission critical environment.
  - type: markdown
    attributes:
      value: |
        ### ðŸš¨ SECURITY INFO
        If you are reporting a security concern, please report it via [our HackerOne page](https://hackerone.com/nextcloud) instead and review our [security policy](https://nextcloud.com/security/).
        This allows us to coordinate the fix and release without potentially exposing all Nextcloud servers and users in the meantime.
        It also may qualify your report for a bug bounty reward.
        Thank you for helping make Nextcloud more secure!
  - type: checkboxes
    id: before-posting
    attributes:
      label: "âš ï¸ This issue respects the following points: âš ï¸"
      description: All conditions are **required**. Your issue can be closed if these are checked incorrectly.
      options:
        - label: This is a **bug**, not a question or a configuration/webserver/proxy issue.
          required: true
        - label: This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
          required: true
        - label: Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
          required: true
        - label: I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: |
        Provide a description of the bug you're experiencing.
        Don't just expect someone will guess what your specific problem is and provide full details.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better your description is _(go 'here', click 'there'...)_ the fastest you'll get an _(accurate)_ answer.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen instead.
    validations:
      required: true
  - type: dropdown
    id: nextcloud-version
    attributes:
      label: Nextcloud Server version
      description: |
        Select Nextcloud Server version.
        _Versions not listed here are not maintained and not supported anymore_
      options:
        - "29"
        - "30"
        - "31"
        - "master"
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Operating system
      description: |
        Select operating system where Nextcloud Server is installed.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "Debian/Ubuntu"
        - "RHEL/CentOS"
        - "Other"
  - type: dropdown
    id: php
    attributes:
      label: PHP engine version
      description: |
        Select PHP engine version serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "PHP 8.4"
        - "PHP 8.3"
        - "PHP 8.2"
        - "PHP 8.1"
        - "Other"
  - type: dropdown
    id: webserver
    attributes:
      label: Web server
      description: |
        Select Webserver serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "Apache (supported)"
        - "Nginx"
        - "Other"
  - type: dropdown
    id: database
    attributes:
      label: Database engine version
      description: |
        Select Database engine serving Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - "MySQL"
        - "MariaDB"
        - "PostgreSQL"
        - "SQlite"
        - "Oracle"
        - "Other"
  - type: dropdown
    id: fresh
    attributes:
      label: Is this bug present after an update or on a fresh install?
      description: |
        Select if bug is present after an update or on a fresh install.
      options:
        - "Updated from a MINOR version (ex. 32.0.1 to 32.0.2)"
        - "Upgraded to a MAJOR version (ex. 31 to 32)"
        - "Fresh Nextcloud Server install"
  - type: dropdown
    id: encryption
    attributes:
      label: Are you using the Nextcloud Server Encryption module?
      description: Select if encryption is Enabled on your Nextcloud Server.
      options:
        - "Encryption is Enabled"
        - "Encryption is Disabled"
  - type: checkboxes
    id: users
    attributes:
      label: What user-backends are you using?
      description: |
        Select **all** user-backends Enabled on your Nextcloud Server.
        _Describe in the "Additional info" section if you chose "Other"._
      options:
      - label: "Default user-backend _(database)_"
      - label: "LDAP/ Active Directory"
      - label: "SSO - SAML"
      - label: "Other"
  - type: textarea
    id: configs
    attributes:
      label: Configuration report
      description: |
        Provide information about your configuration.
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ config:list system
        php occ config:list system
        ./occ config:list system
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: json
  - type: textarea
    id: apps
    attributes:
      label: List of activated Apps
      description: |
        Provide information about your apps.
        To get this information, execute one of the following commands on the CLI:
        ```shell
        sudo -u www-data php occ app:list
        php occ app:list
        ./occ app:list
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: nextcloud-signingstatus
    attributes:
      label: Nextcloud Signing status
      description: |
        Provide Nextcloud Signing status.
        First, login as Admin user into your Nextcloud, then access this URL:
        ```shell
        https://yournextcloud.tld/index.php/settings/integrity/failed
        ```
        > NOTE: This will be automatically formatted into code for better readability.
      render: shell
  - type: textarea
    id: nextcloud-log
    attributes:
      label: Nextcloud Logs
      description: |
        Provide relevant Nextcloud log entries (e.g. from the time period you reproduced the problem).
        Copy full individual entries from `data/nextcloud.log` or use `Copy raw entry` from `/settings/admin/logging` section:
        > NOTE: This will be automatically formatted into code for better readability.
      render: json
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Any additional information related to the issue (ex. browser console errors, software versions).
