<?php
/**
 * This file has been @generated by a phing task from CLDR version 993632df2f5d6a2d33cbbf40d922474c2482eaca.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'CM' => 'Cameroun',
);
