<?php
/**
 * This file has been @generated by a phing task from CLDR version 993632df2f5d6a2d33cbbf40d922474c2482eaca.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'AF' => 'Afuganistani',
  'AZ' => 'Azabajani',
  'BJ' => 'Benini',
  'CI' => 'Kodivaa',
  'CX' => 'Kisiwa cha Christmas',
  'CY' => 'Saiprasi',
  'DK' => 'Denmaki',
  'HR' => 'Kroeshia',
  'JO' => 'Yordani',
  'LB' => 'Lebanoni',
  'LI' => 'Lishenteni',
  'LU' => 'Lasembagi',
  'LV' => 'Lativia',
  'MA' => 'Moroko',
  'MM' => 'Myama',
  'MV' => 'Maldivi',
  'NE' => 'Nijeri',
  'NG' => 'Nijeria',
  'NO' => 'Norwe',
  'NP' => 'Nepali',
  'OM' => 'Omani',
  'PR' => 'Puetoriko',
  'QA' => 'Katari',
  'SD' => 'Sudani',
  'ST' => 'Sao Tome na Prinsipe',
  'TD' => 'Chadi',
  'TL' => 'Timori ya Mashariki',
  'VN' => 'Vietnamu',
);
