OC.L10N.register(
    "files_versions",
    {
    "Could not revert: %s" : "Невозможно откатить: %s",
    "Versions" : "Версии",
    "Failed to revert {file} to revision {timestamp}." : "Не удалось откатить {file} к ревизии {timestamp}.",
    "_%n byte_::_%n bytes_" : ["%n байт","%n байта","%n байт","%n байт"],
    "Restore" : "Откатить",
    "No earlier versions available" : "Нет более ранних версий…",
    "More versions …" : "Ещё версии…",
    "This application automatically maintains older versions of files that are changed." : "Это приложение автоматически поддерживает старые версии файлов, которые были изменены.",
    "This application automatically maintains older versions of files that are changed. When enabled, a hidden versions folder is provisioned in every user’s directory and is used to store old file versions. A user can revert to an older version through the web interface at any time, with the replaced file becoming a version. The app automatically manages the versions folder to ensure the user doesn’t run out of Quota because of versions.\n\t\tIn addition to the expiry of versions, the versions app makes certain never to use more than 50% of the user’s currently available free space. If stored versions exceed this limit, the app will delete the oldest versions first until it meets this limit. More information is available in the Versions documentation." : "Это приложение автоматически поддерживает старые версии файлов, которые были изменены. Когда приложение включено, папка скрытых версий будет в каталоге каждого пользователя и используется для хранения старых версий файлов. Пользователь может в любой момент вернуться к старой версии через веб-интерфейс, при этом файл с новой версией будет заменён файлом старой версии. Приложение автоматически управляет папкой версий, чтобы гарантировать, что у пользователя не закончится дисковая квота из-за обилия версий. В дополнение к истечению срока действия версии, данной приложение не позволяет использовать более 50% свободного места, в настоящее время доступного пользователю. Если сохраненные версии превышают этот предел, приложение сначала удалит самые старые версии, пока не достигнет этого предела. Дополнительная информация доступна в документации в разделе \"Версии\".",
    "This application automatically maintains older versions of files that are changed. When enabled, a hidden versions folder is provisioned in every user’s directory and is used to store old file versions. A user can revert to an older version through the web interface at any time, with the replaced file becoming a version. The app automatically manages the versions folder to ensure the user doesn’t run out of Quota because of versions.\nIn addition to the expiry of versions, the versions app makes certain never to use more than 50% of the user’s currently available free space. If stored versions exceed this limit, the app will delete the oldest versions first until it meets this limit. More information is available in the Versions documentation." : "Это приложение автоматически поддерживает старые версии файлов, которые были изменены. Когда приложение включено, папка скрытых версий будет в каталоге каждого пользователя и используется для хранения старых версий файлов. Пользователь может в любой момент вернуться к старой версии через веб-интерфейс, при этом файл с новой версией будет заменён файлом старой версии. Приложение автоматически управляет папкой версий, чтобы гарантировать, что у пользователя не закончится дисковая квота из-за обилия версий. В дополнение к истечению срока действия версии, данной приложение не позволяет использовать более 50% свободного места, в настоящее время доступного пользователю. Если сохраненные версии превышают этот предел, приложение сначала удалит самые старые версии, пока не достигнет этого предела. Дополнительная информация доступна в документации в разделе \"Версии\"."
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
