OC.L10N.register(
    "files_versions",
    {
    "Could not revert: %s" : "Geri alınamadı: %s",
    "Versions" : "Sürümler",
    "Failed to revert {file} to revision {timestamp}." : "{file} dosyası {timestamp} sürümüne geri alınamadı.",
    "_%n byte_::_%n bytes_" : ["%n bayt","%n bayt"],
    "Restore" : "Geri yükle",
    "No earlier versions available" : "Kullanılabilecek daha önceki bir sürüm yok",
    "More versions …" : "Diğer sürümler ...",
    "This application automatically maintains older versions of files that are changed." : "Bu uygulama değiştirilen dosyaların önceki sürümlerini otomatik olarak izler ve saklar.",
    "This application automatically maintains older versions of files that are changed. When enabled, a hidden versions folder is provisioned in every user’s directory and is used to store old file versions. A user can revert to an older version through the web interface at any time, with the replaced file becoming a version. The app automatically manages the versions folder to ensure the user doesn’t run out of Quota because of versions.\n\t\tIn addition to the expiry of versions, the versions app makes certain never to use more than 50% of the user’s currently available free space. If stored versions exceed this limit, the app will delete the oldest versions first until it meets this limit. More information is available in the Versions documentation." : "Bu uygulama değiştirilen dosyaların önceki sürümlerini otomatik olarak izler ve saklar. etkinleştirildiğinde, dosya sürümlerini saklamak için her kullanıcının klasörlerinde gizli bir versions klasörü oluşturulur. Kullanıcılar web arayüzünü kullanarak istedikleri zaman dosyalarının daha önceki sürümlerine geri dönebilirler. Uygulama versions klasörünü otomatik olarak düzenler ve önceki dosya sürümleri nedeniyle kullanıcının kotasının dolmasını engeller.\n\t\tSürümlerin belirli bir süreyle saklanmasının yanında, sürümler uygulaması hiç bir zaman kullanıcı depolama alanının %50 değerinden fazlasının kullanılmamasını sağlar. Depolanan sürüm dosyalarının sayısı bu sınırlamanın üzerine çıkarsa uygulama sınır değerine geri dönene kadar en eski sürüm dosyalarını siler. Ayrıntılı bilgi almak için Sürümler uygulamasının belgelerine bakabilirsiniz.",
    "This application automatically maintains older versions of files that are changed. When enabled, a hidden versions folder is provisioned in every user’s directory and is used to store old file versions. A user can revert to an older version through the web interface at any time, with the replaced file becoming a version. The app automatically manages the versions folder to ensure the user doesn’t run out of Quota because of versions.\nIn addition to the expiry of versions, the versions app makes certain never to use more than 50% of the user’s currently available free space. If stored versions exceed this limit, the app will delete the oldest versions first until it meets this limit. More information is available in the Versions documentation." : "Bu uygulama değiştirilen dosyaların önceki sürümlerini otomatik olarak izler ve saklar. etkinleştirildiğinde, dosya sürümlerini saklamak için her kullanıcının klasörlerinde gizli bir versions klasörü oluşturulur. Kullanıcılar web arayüzünü kullanarak istedikleri zaman dosyalarının daha önceki sürümlerine geri dönebilirler. Uygulama versions klasörünü otomatik olarak düzenler ve önceki dosya sürümleri nedeniyle kullanıcının kotasının dolmasını engeller.\nSürümlerin belirli bir süreyle saklanmasının yanında, sürümler uygulaması hiç bir zaman kullanıcı depolama alanının %50 değerinden fazlasının kullanılmamasını sağlar. Depolanan sürüm dosyalarının sayısı bu sınırlamanın üzerine çıkarsa uygulama sınır değerine geri dönene kadar en eski sürüm dosyalarını siler. Ayrıntılı bilgi almak için Sürümler uygulamasının belgelerine bakabilirsiniz."
},
"nplurals=2; plural=(n > 1);");
