<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitLookupServerConnector
{
    public static $firstCharsPsr4 = array (
        'O' => true,
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\LookupServerConnector\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob' => __DIR__ . '/..' . '/../lib/BackgroundJobs/RetryJob.php',
        'OCA\\LookupServerConnector\\UpdateLookupServer' => __DIR__ . '/..' . '/../lib/UpdateLookupServer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->firstCharsPsr4 = ComposerStaticInitLookupServerConnector::$firstCharsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitLookupServerConnector::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitLookupServerConnector::$classMap;

        }, null, ClassLoader::class);
    }
}
