<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  212521 => 'Casablanca/Maroc Central',
  2125233 => 'Mohammedia/El Jadida',
  2125234 => 'Settat',
  2125246 => 'Safi/El Youssoufia',
  212525 => 'Maroc Sud',
  2125282 => 'Agadir/Inezgane/Ait Melou',
  2125283 => 'Inezgane/Taroudannt',
  2125285 => 'Taroudannt/Oulad Teima',
  2125288 => 'Es-Semara/Agadir/Tarfaya',
  2125289 => 'Laayoune/Dakhla',
  21252980 => 'Marrakech et alentours',
  21252990 => 'Agadir et alentours',
  212530 => 'Rabat/Kénitra',
  212531 => 'Tanger/Tétouan/Larache/Al Hoceima/Cherfchaouen',
  212532 => 'Fès/Oujda/Meknès/Taza/Nador/Errachidia',
  2125366 => 'Oujda/Figuig',
  2125367 => 'Oujda/Bouarfa',
  2125380 => 'Rabat et alentours',
  21253880 => 'Tanger et alentours',
  21253890 => 'Fès/Maknès et alentours',
  2125393 => 'Tanger',
  2125399 => 'Tanger/Larache/Al Hoceima',
);
