<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  4122 => 'Genève',
  4133 => 'Thoune',
  4152 => 'Winterthour',
  4161 => 'Bâle',
  4171 => 'St. Gall',
  4181 => 'Coire',
);
