<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitNominatim
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\Nominatim\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Nominatim\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\Nominatim\\AppInfo\\Application' => __DIR__ . '/..' . '/../lib/AppInfo/Application.php',
        'OCA\\Nominatim\\LocationProvider' => __DIR__ . '/..' . '/../lib/LocationProvider.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitNominatim::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitNominatim::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitNominatim::$classMap;

        }, null, ClassLoader::class);
    }
}
