OC.L10N.register(
    "webhook_listeners",
    {
    "Ephemeral webhook authentication" : "Εφήμερη ταυτοποίηση webhook",
    "Webhooks" : "Webhooks",
    "Nextcloud Webhook Support" : "Υποστήριξη Webhook Nextcloud",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Αποστολή ειδοποιήσεων σε εξωτερικές υπηρεσίες όταν συμβαίνει κάτι σημαντικό, όπως όταν αλλάζουν ή ενημερώνονται αρχεία.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms and automating workflows.\n\nThe app works by monitoring Nextcloud's event system and dispatching HTTP requests (webhooks) containing relevant event data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\nAdministrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list currently configured webhooks. There are no Web UI settings." : "Ρυθμίστε webhooks που ειδοποιούν αυτόματα εξωτερικές υπηρεσίες κάθε φορά που συμβαίνουν συγκεκριμένα συμβάντα - όπως αλλαγές αρχείων - εντός του Nextcloud. Διαμορφώνοντας αυτά τα webhooks, οι διαχειριστές μπορούν να καθορίσουν ποιες ενέργειες στο δικό τους στιγμιότυπο Nextcloud θα πρέπει να ενεργοποιούν ειδοποιήσεις και πού πρέπει να αποστέλλονται αυτές οι ειδοποιήσεις, επιτρέποντας την απρόσκοπτη ενοποίηση με άλλες πλατφόρμες και την αυτοματοποίηση των ροών εργασίας.\n\nΗ εφαρμογή λειτουργεί παρακολουθώντας το σύστημα συμβάντων του Nextcloud και αποστέλλοντας αιτήματα HTTP (webhooks) που περιέχουν σχετικά δεδομένα συμβάντων στα καθορισμένα τελικά σημεία (endpoints) κάθε φορά που λαμβάνει χώρα ένα διαμορφωμένο συμβάν. Αυτή η προσέγγιση διευκολύνει τη σύνδεση του Nextcloud με εξωτερικά εργαλεία, επιτρέποντας αλληλεπιδράσεις σε πραγματικό χρόνο χωρίς να χρειάζεται χειροκίνητος έλεγχος για ενημερώσεις ή αλλαγές.\n\nΟι διαχειριστές μπορούν να διαμορφώσουν ακροατές webhook (webhook listeners) μέσω του OCS API της εφαρμογής. Η εφαρμογή παρέχει επίσης ένα εργαλείο γραμμής εντολών (CLI) για την προβολή των τρεχόντων διαμορφωμένων webhooks. Δεν υπάρχουν ρυθμίσεις στο περιβάλλον εργασίας χρήστη (Web UI).",
    "Nextcloud webhook support" : "Υποστήριξη webhook Nextcloud"
},
"nplurals=2; plural=(n != 1);");
