OC.L10N.register(
    "webhook_listeners",
    {
    "Ephemeral webhook authentication" : "Ephemeral webhook authentication",
    "Webhooks" : "Webhooks",
    "Nextcloud Webhook Support" : "Nextcloud Webhook Support",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Send notifications to external services whenever something important happens, like when files are changed or updated.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms and automating workflows.\n\nThe app works by monitoring Nextcloud's event system and dispatching HTTP requests (webhooks) containing relevant event data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\nAdministrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list currently configured webhooks. There are no Web UI settings." : "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms and automating workflows.\n\nThe app works by monitoring Nextcloud's event system and dispatching HTTP requests (webhooks) containing relevant event data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\nAdministrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list currently configured webhooks. There are no Web UI settings.",
    "Nextcloud webhook support" : "Nextcloud webhook support"
},
"nplurals=2; plural=(n != 1);");
