OC.L10N.register(
    "webhook_listeners",
    {
    "Webhooks" : "Crúcaí gréasáin",
    "Nextcloud Webhook Support" : "Tacaíocht Webhook Nextcloud",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Seol fógraí chuig seirbhísí seachtracha aon uair a tharlaíonn rud éigin tábhachtach, amhail nuair a athraítear nó a nuashonraítear comhaid.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur \n        within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance \n        should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms \n        and automating workflows.\n\n        The app works by monitoring Nextcloud’s event system and dispatching HTTP requests (webhooks) containing relevant event \n        data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud \n        with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\n        Administrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list \n        currently configured webhooks. There are no Web UI settings." : "Socraigh crúcaí gréasáin a chuireann seirbhísí seachtracha ar an eolas go huathoibríoch aon uair a tharlaíonn imeachtaí áirithe - amhail athruithe comhaid - laistigh de Nextcloud. Trí na crúcaí gréasáin seo a chumrú, is féidir le riarthóirí a shonrú cé na gníomhartha ina gcás Nextcloud ba chóir fógraí a spreagadh agus cá háit ar chóir na fógraí sin a sheoladh, rud a chuireann ar chumas comhtháthú gan uaim le hardáin eile agus sreafaí oibre a uathoibriú.\n\nOibríonn an aip trí chóras imeachtaí Nextcloud a mhonatóiriú agus iarratais HTTP (crúcaí gréasáin) ina bhfuil sonraí imeachta ábhartha a sheoladh chuig na críochphointí sonraithe aon uair a tharlaíonn imeacht cumraithe. Leis an gcur chuige seo, is furasta Nextcloud a nascadh le huirlisí seachtracha, rud a ligeann d’idirghníomhaíochtaí fíor-ama gan gá le seiceáil de láimh le haghaidh nuashonruithe nó athruithe.\n\nIs féidir le riarthóirí éisteoirí crúcaí gréasáin a chumrú trí OCS API na haipe. Soláthraíonn an aip uirlis líne ordaithe freisin chun crúcaí gréasáin atá cumraithe faoi láthair a liostáil Níl aon socruithe Chomhéadain Gréasáin ann.",
    "Nextcloud webhook support" : "Tacaíocht cúnta gréasáin Nextcloud"
},
"nplurals=5; plural=(n==1 ? 0 : n==2 ? 1 : n<7 ? 2 : n<11 ? 3 : 4);");
