OC.L10N.register(
    "webhook_listeners",
    {
    "Ephemeral webhook authentication" : "Autenticación efímera por punto de ancoraxe web",
    "Webhooks" : "Puntos de ancoraxe web",
    "Nextcloud Webhook Support" : "Compatibilidade para Puntos de ancoraxe web de NextCloud",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Envía notificacións a servizos externos cada vez que ocorre algo importante, como cando se modifican ou actualizan ficheiros.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms and automating workflows.\n\nThe app works by monitoring Nextcloud's event system and dispatching HTTP requests (webhooks) containing relevant event data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\nAdministrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list currently configured webhooks. There are no Web UI settings." : "Configurar puntos de ancoraxe web que notifiquen automaticamente aos servizos externos cada vez que se produzan certos eventos, como cambios de ficheiros, dentro de Nextcloud. Ao configurar estes puntos de ancoraxe web, os administradores poden especificar que accións na súa instancia Nextcloud deben activar notificacións e onde deben enviarse esas notificacións, permitindo unha integración perfecta con outras plataformas e automatizando os fluxos de traballo.\n\nA aplicación funciona monitorizando o sistema de eventos de Nextcloud e enviando solicitudes HTTP (ancoraxes web) que conteñen datos de eventos relevantes aos puntos finais especificados cada vez que ocorre un evento configurado. Este enfoque facilita a conexión de Nextcloud con ferramentas externas, permitindo interaccións en tempo real sen necesidade de comprobar manualmente actualizacións ou cambios.\n\nOs administradores poden configurar os oíntes de ancoraxes web a través da API OCS da aplicación. A aplicación tamén fornece unha ferramenta de liña de ordes para listar ancoraxes web configurados actualmente. Non hai axustes de UI web.",
    "Nextcloud webhook support" : "Compatibilidade para Puntos de ancoraxe web de NextCloud"
},
"nplurals=2; plural=(n != 1);");
