OC.L10N.register(
    "webhook_listeners",
    {
    "Ephemeral webhook authentication" : "Privremena autentifikacija web-dojave",
    "Webhooks" : "Web-dojave",
    "Nextcloud Webhook Support" : "Podrška za web-dojave u Nextcloudu",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Šaljite obavijesti vanjskim servisima svaki put kada se dogodi nešto važno, primjerice kada se datoteke promijene ili ažuriraju.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms and automating workflows.\n\nThe app works by monitoring Nextcloud's event system and dispatching HTTP requests (webhooks) containing relevant event data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\nAdministrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list currently configured webhooks. There are no Web UI settings." : "Postavite web-dojave koje automatski obavještavaju vanjske servise svaki put kada se u Nextcloudu dogode određeni događaji – poput promjena datoteka. Konfiguriranjem ovih web-dojava administratori mogu odrediti koje radnje u njihovoj Nextcloud instanci trebaju pokrenuti obavijesti i kamo se te obavijesti šalju, čime se omogućuje neometana integracija s drugim platformama i automatizacija radnih procesa.\n\nAplikacija radi tako da nadzire Nextcloudov sustav događaja i, kada se dogodi konfigurirani događaj, šalje HTTP zahtjeve (web-dojave) s relevantnim podacima o događaju na zadane krajnje točke. Ovakav pristup olakšava povezivanje Nextclouda s vanjskim alatima te omogućuje interakcije u stvarnom vremenu bez potrebe za ručnom provjerom ažuriranja ili promjena.\n\nAdministratori mogu konfigurirati slušatelje web-dojava putem OCS API-ja aplikacije. Aplikacija također pruža alat naredbenog retka za prikaz trenutno konfiguriranih web-dojava. Ne postoje postavke putem web sučelja.",
    "Nextcloud webhook support" : "Podrška za web-dojave u Nextcloudu"
},
"nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;");
