OC.L10N.register(
    "webhook_listeners",
    {
    "Ephemeral webhook authentication" : "Autentikasi webhook sementara",
    "Webhooks" : "Webhook",
    "Nextcloud Webhook Support" : "Dukungan Webhook Nextcloud",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Kirim notifikasi ke layanan eksternal setiap kali sesuatu yang penting terjadi, seperti saat file diubah atau diperbarui.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms and automating workflows.\n\nThe app works by monitoring Nextcloud's event system and dispatching HTTP requests (webhooks) containing relevant event data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\nAdministrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list currently configured webhooks. There are no Web UI settings." : "Siapkan webhook yang secara otomatis memberi tahu layanan eksternal setiap kali peristiwa tertentu - seperti perubahan file - terjadi di dalam Nextcloud. Dengan mengonfigurasi webhook ini, administrator dapat menentukan tindakan mana di instance Nextcloud mereka yang harus memicu notifikasi dan ke mana notifikasi tersebut harus dikirim, sehingga memungkinkan integrasi yang mulus dengan platform lain dan mengotomatiskan alur kerja.\n\nAplikasi ini bekerja dengan memantau sistem peristiwa Nextcloud dan mengirimkan permintaan HTTP (webhook) yang berisi data peristiwa yang relevan ke endpoint yang ditentukan setiap kali peristiwa yang dikonfigurasi terjadi. Pendekatan ini memudahkan untuk menghubungkan Nextcloud dengan alat eksternal, memungkinkan interaksi waktu nyata tanpa perlu memeriksa pembaruan atau perubahan secara manual.\n\nAdministrator dapat mengonfigurasi listener webhook melalui OCS API aplikasi. Aplikasi ini juga menyediakan alat command-line untuk menampilkan daftar webhook yang saat ini dikonfigurasi. Tidak ada pengaturan Web UI.",
    "Nextcloud webhook support" : "Dukungan webhook Nextcloud"
},
"nplurals=1; plural=0;");
