OC.L10N.register(
    "webhook_listeners",
    {
    "Webhooks" : "Webhooks",
    "Nextcloud Webhook Support" : "Suporte para Webhooks do Nextcloud",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Envie notificações para serviços externos sempre que algo importante acontecer, como quando arquivos forem alterados ou atualizados.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur \n        within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance \n        should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms \n        and automating workflows.\n\n        The app works by monitoring Nextcloud’s event system and dispatching HTTP requests (webhooks) containing relevant event \n        data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud \n        with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\n        Administrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list \n        currently configured webhooks. There are no Web UI settings." : "Configure webhooks que notificam automaticamente serviços externos sempre que determinados eventos — como alterações de arquivos — ocorrerem no Nextcloud.\n\nAo configurar esses webhooks, os administradores podem especificar quais ações em sua instância do Nextcloud devem acionar notificações e para onde essas notificações devem ser enviadas, permitindo uma integração perfeita com outras plataformas e automatizando fluxos de trabalho.\n\nO aplicativo funciona monitorando o sistema de eventos do Nextcloud e enviando solicitações HTTP (webhooks) contendo dados relevantes do evento para os endpoints especificados sempre que um evento configurado ocorre.\nEssa abordagem facilita a conexão do Nextcloud com ferramentas externas, permitindo interações em tempo real sem a necessidade de verificar manualmente atualizações ou alterações.\n\nOs administradores podem configurar ouvintes de webhook por meio da API OCS do aplicativo. O aplicativo também fornece uma ferramenta de linha de comando para listar os webhooks configurados atualmente.\n\nNão há configurações na interface web.",
    "Nextcloud webhook support" : "Suporte a webhooks para Nextcloud"
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
