OC.L10N.register(
    "webhook_listeners",
    {
    "Webhooks" : "Viboko vya mtandao",
    "Nextcloud Webhook Support" : "Msaada wa Nextcloud Webhook",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Tuma arifa kwa huduma za nje kila jambo muhimu linapotokea, kama vile faili zinapobadilishwa au kusasishwa.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur \n        within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance \n        should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms \n        and automating workflows.\n\n        The app works by monitoring Nextcloud’s event system and dispatching HTTP requests (webhooks) containing relevant event \n        data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud \n        with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\n        Administrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list \n        currently configured webhooks. There are no Web UI settings." : "Sanidi viboreshaji vya wavuti ambavyo huarifu huduma za nje kiotomatiki wakati wowote matukio fulani - kama vile mabadiliko ya faili - yanapotokea \nndani ya Nextcloud. Kwa kusanidi vijiti hivi vya wavuti, wasimamizi wanaweza kubainisha ni vitendo vipi katika mfano wao wa Nextcloud \ninapaswa kuanzisha arifa na ambapo arifa hizo zinapaswa kutumwa, kuwezesha ujumuishaji usio na mshono na mifumo mingine \nna utiririshaji wa kazi otomatiki.\n\nProgramu inafanya kazi kwa kufuatilia mfumo wa matukio wa Nextcloud na kutuma maombi ya HTTP (webhooks) iliyo na tukio husika. \ndata kwa ncha zilizobainishwa kila tukio lililosanidiwa linapofanyika. Mbinu hii hurahisisha kuunganisha Nextcloud \nna zana za nje, zinazoruhusu mwingiliano wa wakati halisi bila kuhitaji kuangalia mwenyewe masasisho au mabadiliko.\n\nWasimamizi wanaweza kusanidi wasikilizaji wa mtandao kupitia API ya OCS ya programu. Programu pia hutoa zana ya mstari wa amri kuorodhesha \nvijiti vya wavuti vilivyosanidiwa kwa sasa. Hakuna mipangilio ya UI ya Wavuti.",
    "Nextcloud webhook support" : "Msaada wa viboko vya mtandao wa Nextcloud"
},
"nplurals=2; plural=(n != 1);");
