OC.L10N.register(
    "webhook_listeners",
    {
    "Ephemeral webhook authentication" : "Ephemeral internet kancası kimlik doğrulaması",
    "Webhooks" : "İnternet kancaları",
    "Nextcloud Webhook Support" : "Nextcloud internet kancası desteği",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Dosyaların değiştirilmesi veya güncellenmesi gibi önemli bir şey olduğunda dış hizmetlere bildirim gönderin.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur within Nextcloud. By configuring these webhooks, administrators can specify which actions in their Nextcloud instance should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms and automating workflows.\n\nThe app works by monitoring Nextcloud's event system and dispatching HTTP requests (webhooks) containing relevant event data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Nextcloud with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\nAdministrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list currently configured webhooks. There are no Web UI settings." : "Nextcloud üzerinde dosya değişiklikleri gibi belirli olaylar gerçekleştiğinde dış hizmetleri otomatik olarak bilgilendiren internet kancalarını ayarlayın. Bu internet kancalarını yapılandırarak, yöneticiler Nextcloud kopyalarında hangi işlemlerin bildirimleri tetiklemesi gerektiğini ve bu bildirimlerin nereye gönderilmesi gerektiğini belirleyerek diğer platformlarla sorunsuz bütünleştirme sağlayabilir ve iş akışlarını otomatikleştirebilir.\n\nUygulama, Nextcloud olay sistemini izleyerek, yapılandırılmış bir olay gerçekleştiğinde ilgili olay verilerini içeren HTTP isteklerini (internet kancaları) belirtilen uç noktalara göndererek çalışır. Bu yaklaşım, Nextcloud ile dış araçların bağlanmasını kolaylaştırır ve güncellemeleri veya değişiklikleri el ile denetlemeye gerek kalmadan gerçek zamanlı etkileşim kurulmasını sağlar.\n\nYöneticiler, uygulamadaki OCS API ile internet kancası dinleyicilerini yapılandırabilir. Uygulama ayrıca şu anda yapılandırılmış internet kancalarını listelemek için bir komut satırı aracı sağlar. İnternet kullanıcı arayüzü ayarı yoktur.",
    "Nextcloud webhook support" : "Nextcloud internet kancası desteği"
},
"nplurals=2; plural=(n > 1);");
