<?php
return array(
	'ftp'=>array(
		'host'=>'localhost',
		'user'=>'test',
		'password'=>'test',
		'root'=>'/test',
	),
	'webdav'=>array(
		'host'=>'localhost',
		'user'=>'test',
		'password'=>'test',
		'root'=>'/owncloud/files/webdav.php',
	),
	'google'=>array(
		'consumer_key'=>'anonymous',
		'consumer_secret'=>'anonymous',
		'token'=>'test',
		'token_secret'=>'test',
		'root'=>'/google',
	)
);
