# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Code checkers

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: autocheckers-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest-low

    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - '3rdparty/**'
              - '**/appinfo/**'
              - '**/lib/**'
              - '**/templates/**'
              - 'vendor/**'
              - 'vendor-bin/**'
              - 'composer.json'
              - 'composer.lock'
              - '**.php'
              - build/autoloaderchecker.sh

  autoloader:
    runs-on: ubuntu-latest

    needs: changes
    if: needs.changes.outputs.src != 'false'

    name: PHP checkers

    steps:
      - name: Checkout server
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #v2.37.2
        timeout-minutes: 5
        with:
          php-version: '8.3'
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check auto loaders
        run: bash ./build/autoloaderchecker.sh

  autocheckers:
    runs-on: ubuntu-latest-low

    needs: changes
    if: needs.changes.outputs.src != 'false'

    name: Translation and Files checkers

    steps:
      - name: Checkout server
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #v2.37.2
        timeout-minutes: 5
        with:
          php-version: '8.3'
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check translations are JSON decodeable
        run: php ./build/translation-checker.php

      - name: Check translations do not contain triple dot but ellipsis
        run: php ./build/triple-dot-checker.php

      - name: Check .htaccess does not contain invalid changes
        run: php ./build/htaccess-checker.php

      - name: Check that all and only expected files are included
        run: php ./build/files-checker.php

      - name: Check that all shipped apps are linted by psalm
        run: sh ./build/psalm-checker.sh

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: [changes, autoloader, autocheckers]

    if: always()

    name: autocheckers-summary

    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src != 'false' && (needs.autocheckers.result != 'success' || needs.autoloader.result != 'success') }}; then exit 1; fi
