name: Trigger GitLab Image Pipeline

on:
  schedule:
    - cron: "0 15 * * *"

  workflow_run:
    workflows: ["MCLOUD custom server release"]
    types:
      - completed
  workflow_dispatch: # manual

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Nmc deployment image building
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_IMAGE_TRIGGER_TOKEN }}
      run: |
        curl -X POST \
            --fail \
            -F token=$GITLAB_TOKEN \
            -F ref=master \
            https://gitlab.devops.telekom.de/api/v4/projects/37742/trigger/pipeline
