name: Trigger GitLab Image Pipeline

on:
  workflow_run:
    workflows: ["MCLOUD custom server release"]
    types:
      - completed
  workflow_dispatch:  # Manual trigger option

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Nmc deployment image building
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_IMAGE_BUILD }}
      run: |
        curl -X POST \
            --fail \
            -F token=$GITLAB_IMAGE_BUILD \
            -F ref=master \
            https://gitlab.devops.telekom.de/api/v4/projects/37742/trigger/pipeline
