# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Psalm static code analysis

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*
    paths:
      - '.github/workflows/static-code-analysis.yml'
      - '**.php'

permissions:
  contents: read

concurrency:
  group: static-code-analysis-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest-low

    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - '3rdparty/**'
              - '**/appinfo/**'
              - '**/lib/**'
              - '**/templates/**'
              - 'vendor/**'
              - 'vendor-bin/**'
              - 'composer.json'
              - 'composer.lock'
              - '**.php'

  static-code-analysis:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.src != 'false' && github.event_name != 'push' && github.repository_owner != 'nextcloud-gmbh' }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f #v2.37.0
        timeout-minutes: 5
        with:
          php-version: '8.2'
          extensions: apcu,ctype,curl,dom,fileinfo,ftp,gd,imagick,intl,json,ldap,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer i

      - name: Psalm
        run: composer run psalm -- --threads=1 --monochrome --no-progress --output-format=github --update-baseline

      - name: Show potential changes in Psalm baseline
        if: always()
        run: git diff --exit-code -- . ':!lib/composer'

  static-code-analysis-security:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.src != 'false' && github.repository_owner != 'nextcloud-gmbh' }}

    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f #v2.37.0
        timeout-minutes: 5
        with:
          php-version: '8.2'
          extensions: ctype,curl,dom,fileinfo,ftp,gd,imagick,intl,json,ldap,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none

      - name: Composer install
        run: composer i

      - name: Psalm taint analysis
        run: composer run psalm:security -- --threads=1 --monochrome --no-progress --output-format=github --update-baseline --report=results.sarif

      - name: Show potential changes in Psalm baseline
        if: always()
        run: git diff --exit-code -- . ':!lib/composer'

      - name: Upload Security Analysis results to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v3
        with:
          sarif_file: results.sarif

  static-code-analysis-ocp:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.src != 'false' && github.event_name != 'push' && github.repository_owner != 'nextcloud-gmbh' }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f #v2.37.0
        timeout-minutes: 5
        with:
          php-version: '8.2'
          extensions: ctype,curl,dom,fileinfo,gd,imagick,intl,json,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer i

      - name: Psalm
        run: composer run psalm:ocp -- --threads=1 --monochrome --no-progress --output-format=github --update-baseline

      - name: Show potential changes in Psalm baseline
        if: always()
        run: git diff --exit-code -- . ':!lib/composer'

  static-code-analysis-ncu:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.src != 'false' && github.event_name != 'push' && github.repository_owner != 'nextcloud-gmbh' }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f #v2.37.0
        timeout-minutes: 5
        with:
          php-version: '8.2'
          extensions: ctype,curl,dom,fileinfo,gd,imagick,intl,json,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer i

      - name: Psalm
        run: composer run psalm:ncu -- --threads=1 --monochrome --no-progress --output-format=github

  static-code-analysis-strict:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.src != 'false' && github.event_name != 'push' && github.repository_owner != 'nextcloud-gmbh' }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f #v2.37.0
        with:
          php-version: '8.2'
          extensions: ctype,curl,dom,fileinfo,gd,imagick,intl,json,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer i

      - name: Psalm
        run: composer run psalm:strict -- --threads=1 --monochrome --no-progress --output-format=github

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: [changes, static-code-analysis, static-code-analysis-security, static-code-analysis-ocp, static-code-analysis-ncu, static-code-analysis-strict]

    if: always()

    name: static-code-analysis-summary

    steps:
      - name: Summary status
        run: |
          if ${{ needs.changes.outputs.src != 'false' && (
            needs.static-code-analysis-security.result != 'success' ||
            (github.event_name != 'push' && (
              needs.static-code-analysis.result != 'success' ||
              needs.static-code-analysis-ocp.result != 'success' ||
              needs.static-code-analysis-ncu.result != 'success' ||
              needs.static-code-analysis-strict.result != 'success'
            ))
          ) }}; then
            exit 1
          fi
