<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  22245 => 'Nouakchott',
  2224513 => 'Néma',
  2224515 => 'Aioun',
  2224533 => 'Kaédi',
  2224534 => 'Sélibaby',
  2224537 => 'Aleg',
  2224544 => 'Zouérat',
  2224546 => 'Atar',
  2224550 => 'Boghé',
  2224563 => 'Kiffa',
  2224569 => 'Rosso/Tidjikja',
  2224574 => 'Nouadhibou',
);
