<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  224302 => 'Fria',
  2243031 => 'Boké',
  2243032 => 'Kamsar',
  2243041 => 'Conakry',
  2243042 => 'Sangoya',
  2243043 => 'Conakry',
  2243045 => 'Conakry',
  2243046 => 'Boussoura',
  2243047 => 'Conakry',
  2243051 => 'Labé',
  2243053 => 'Pita',
  2243061 => 'Kindia',
  22430613 => 'Télimélé',
  2243068 => 'Mamou',
  2243069 => 'Dalaba',
  224307 => 'Kankan',
  224308 => 'Faranah',
  2243091 => 'N\'Zérékoré',
  2243094 => 'Macenta',
  2243097 => 'Guéckédou',
  2243098 => 'Kissidougou',
);
