<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  2392220 => 'Santo Amaro',
  2392221 => 'Água Grande',
  2392222 => 'Água Grande',
  2392223 => 'Água Grande',
  2392224 => 'Água Grande',
  2392225 => 'Água Grande',
  2392226 => 'Água Grande',
  2392227 => 'Água Grande',
  2392228 => 'Água Grande',
  2392231 => 'Guadalupe',
  2392233 => 'Neves, Santa Catarina',
  239224 => 'Água Grande',
  2392251 => 'Autonomous Region of Príncipe',
  2392261 => 'Angolares, Porto Alegre',
  2392265 => 'Santana, Ribeira Afonso',
  2392271 => 'Trindade',
  2392272 => 'Madalena',
  239228 => 'Água Grande',
  239229 => 'Água Grande',
);
