<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  260211 => 'Lusaka Province',
  260212 => 'Ndola/Copperbelt and Luapula Provinces',
  260213 => 'Livingstone/Southern Province',
  260214 => 'Kasama/Northern Province',
  260215 => 'Kabwe/Central Province',
  260216 => 'Chipata/Eastern Province',
  260217 => 'Solwezi/Western Province',
  260218 => 'Mongu/North-Western Province',
);
