<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  6852 => 'Apia',
  6853 => 'Apia',
  6854 => 'Upolu Rural',
  6855 => 'Savaii',
  68561 => 'Apia',
  68562 => 'Apia',
  68563 => 'Apia',
  68564 => 'Apia',
  68565 => 'Apia',
  68566 => 'Apia',
  68567 => 'Apia',
  68568 => 'Apia',
  68569 => 'Apia',
);
